import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { createServer } from "node:http";
import { mkdtempSync,mkdirSync,readFileSync,realpathSync,readdirSync,rmSync,writeFileSync } from "node:fs";
import { homedir,tmpdir } from "node:os";
import { join,resolve } from "node:path";
import { spawnSync } from "node:child_process";
const CONTRACT="proflow.browser-extension.self-reload.v1", ID="eehdadpmjffomabiedcjijiakconalab", ROOT="/Users/agent/Desktop/proton-workspace";
const arg=(n,f)=>{const i=process.argv.indexOf(n);return i>=0&&process.argv[i+1]?process.argv[i+1]:f};
const real=p=>{try{return realpathSync(p)}catch{return resolve(p)}};
function registration(chrome,id,load){const out=[];for(const e of readdirSync(chrome,{withFileTypes:true})){if(!e.isDirectory())continue;try{const j=JSON.parse(readFileSync(join(chrome,e.name,"Secure Preferences"),"utf8"));const r=j?.extensions?.settings?.[id];if(r&&typeof r.path==="string"&&real(r.path)===real(load))out.push({profile:e.name,path:r.path})}catch{}}if(out.length!==1)throw new Error(out.length?"BROWSER_EXTENSION_REGISTRATION_NOT_UNIQUE":"BROWSER_EXTENSION_REGISTRATION_NOT_FOUND");return out[0]}
function url(id,action,callback,nonce){const u=new URL(`chrome-extension://${id}/extension/options.html`);for(const [k,v] of Object.entries({proflowAutomation:action,extensionId:id,callback,nonce}))u.searchParams.set(k,v);return u.href}
function report(v,a,id){if(!v||v.contract!==CONTRACT||v.action!==a||v.extensionId!==id||!v.version)throw new Error("AUTOMATION_REPORT_INVALID");return v}
async function server(id){const wait=new Map(),s=createServer((req,res)=>{const w=wait.get(req.url||"");if(!w||req.method!=="POST"){res.statusCode=404;res.end();return}let b="";req.on("data",c=>b+=c);req.on("end",()=>{try{w.resolve(report(JSON.parse(b),w.action,id));wait.delete(req.url);res.statusCode=204;res.end()}catch(e){res.statusCode=400;res.end();w.reject(e)}})});await new Promise((ok,no)=>{s.once("error",no);s.listen(0,"127.0.0.1",ok)});const port=s.address().port;return {s,ask(action,ms){const nonce=randomUUID(),p=`/proflow/${nonce}`,callback=`http://127.0.0.1:${port}${p}`;return {nonce,callback,promise:new Promise((resolve,reject)=>{const t=setTimeout(()=>{wait.delete(p);reject(new Error(`AUTOMATION_CALLBACK_TIMEOUT:${action}`))},ms);wait.set(p,{action,resolve:v=>{clearTimeout(t);resolve(v)},reject})})}}}}
function open(href){const r=spawnSync("/usr/bin/open",["-g","-a","Google Chrome",href],{encoding:"utf8"});if(r.status!==0)throw new Error("CHROME_OPEN_FAILED")}
async function collect(s,id,action,ms){const p=s.ask(action,ms);open(url(id,action,p.callback,p.nonce));return await p.promise}
async function self(){const t=mkdtempSync(join(tmpdir(),"proflow-reload-"));try{const load=join(t,"w",".proflow","deployment","browser-extension","execution-browser-extension"),chrome=join(t,"Chrome");mkdirSync(load,{recursive:true});mkdirSync(join(chrome,"Default"),{recursive:true});writeFileSync(join(chrome,"Default","Secure Preferences"),JSON.stringify({extensions:{settings:{[ID]:{path:load}}}}));assert.equal(registration(chrome,ID,load).profile,"Default");assert.match(url(ID,"probe","http://127.0.0.1/x","n"),/^chrome-extension:\/\//);console.log("BROWSER_SELF_RELOAD_SELF_TEST=PASS")}finally{rmSync(t,{recursive:true,force:true})}}
async function main(){if(process.argv.includes("--self-test"))return self();const workspace=arg("--workspace",ROOT),id=arg("--extension-id",ID),ms=Number(arg("--timeout-ms","8000")),load=join(workspace,".proflow","deployment","browser-extension","execution-browser-extension"),expected=String(JSON.parse(readFileSync(join(load,"manifest.json"),"utf8")).version||"");if(!expected)throw new Error("WORKSPACE_EXTENSION_VERSION_MISSING");registration(join(homedir(),"Library","Application Support","Google","Chrome"),id,load);const cb=await server(id);try{let v=await collect(cb,id,"probe",ms);if(v.version===expected){console.log("BROWSER_SELF_RELOAD=PASS ALREADY_CURRENT");return}await collect(cb,id,"reload",ms);for(let i=0;i<3;i++){await new Promise(r=>setTimeout(r,i?700:900));v=await collect(cb,id,"probe",ms);if(v.version===expected){console.log("BROWSER_SELF_RELOAD=PASS RELOADED");return}}throw new Error(`BROWSER_SELF_RELOAD_VERSION_MISMATCH:${v.version}->${expected}`)}finally{await new Promise(r=>cb.s.close(r))}}
main().catch(e=>{console.error(`BROWSER_SELF_RELOAD=FAIL ${e instanceof Error?e.message:String(e)}`);process.exit(1)});
